/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;



import Models.Usuario;
import Services.Conexao;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;


    
public class ConfiguracaoAdmin extends javax.swing.JInternalFrame {
    CriarEleicao telaCriarEleicao = null;
    CadastrarUsuario telaCadastrarUsuario = null;
    CriarCandidatura telaCriarCandidatura = null;
    private Usuario adminLogado = null;

    public TreeMap<String, Integer> campusMap = new TreeMap<>();
    
    public ConfiguracaoAdmin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCriarEleicao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEleicoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnCadastrarUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnCandidatarNovoUsuario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCandidatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbxCampus = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 51, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.highlight")));
        setClosable(true);
        setTitle("Tela de Cadastro - Admin");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 204));
        jTabbedPane1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.light")));

        btnCriarEleicao.setBackground(new java.awt.Color(51, 102, 255));
        btnCriarEleicao.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnCriarEleicao.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnCriarEleicao.setText("Criar Eleição");
        btnCriarEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEleicaoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jButton2.setText("Excluir eleição");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriarEleicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCriarEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblEleicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEleicoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblEleicoes);

        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel1.setText("Eleições atualmente disponíveis :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eleições", null, jPanel1, "");

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        jPanel2.setAutoscrolls(true);
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jPanel5.setBackground(new java.awt.Color(0, 51, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.light")));

        btnCadastrarUsuario.setBackground(new java.awt.Color(51, 102, 255));
        btnCadastrarUsuario.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnCadastrarUsuario.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnCadastrarUsuario.setText("Cadastrar novo usuario");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setBackground(new java.awt.Color(51, 102, 255));
        btnExcluirUsuario.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnExcluirUsuario.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnExcluirUsuario.setText("Excluir usuario");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        btnEditarUsuario.setBackground(new java.awt.Color(51, 102, 255));
        btnEditarUsuario.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnEditarUsuario.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnEditarUsuario.setText("Editar usuario");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblUsuarios);

        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel2.setText("Usuarios cadastrados atualmente:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuarios", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        jPanel6.setBackground(new java.awt.Color(0, 51, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.light")));

        btnCandidatarNovoUsuario.setBackground(new java.awt.Color(51, 102, 255));
        btnCandidatarNovoUsuario.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnCandidatarNovoUsuario.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnCandidatarNovoUsuario.setText("Candidatar novo usuario");
        btnCandidatarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatarNovoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCandidatarNovoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCandidatarNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCandidatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tblCandidatos);

        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel3.setText("Usuarios que atualmente são candidatos:  ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Candidatura", jPanel3);

        jPanel7.setBackground(new java.awt.Color(0, 51, 204));

        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel4.setText("Visualizando configurações para o campus:");

        cbxCampus.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        cbxCampus.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        cbxCampus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCampusItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbxCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEleicaoActionPerformed
        inicializarCriarEleicao();
    }//GEN-LAST:event_btnCriarEleicaoActionPerformed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        inicializarCadastrarUsuario();
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    preencherCombBoxDescricao();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        if (tblUsuarios.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Selecione um usuario para excluir !!!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        excluirUsuario(Integer.valueOf(tblUsuarios.getModel().getValueAt(tblUsuarios.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void cbxCampusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCampusItemStateChanged
      pesquisarTabelas(campusMap.get(cbxCampus.getSelectedItem().toString()));
    }//GEN-LAST:event_cbxCampusItemStateChanged

    private void btnCandidatarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatarNovoUsuarioActionPerformed
      inicializarCriarCandidatura();
    }//GEN-LAST:event_btnCandidatarNovoUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       excluirEleicao();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        if (tblUsuarios.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(rootPane, "É necessário escolher um usuario para edição !!", "Atenção !!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Conexao con = new Conexao();
        
       Usuario usuarioEdicao = con.getUsuario(new Integer(tblUsuarios.getModel().getValueAt(tblUsuarios.getSelectedRow(), 0).toString()));
       
            JDesktopPane framePrincipal = this.getDesktopPane();
            
            if(telaCadastrarUsuario == null )        
        {
            telaCadastrarUsuario = new CadastrarUsuario();
            
            telaCadastrarUsuario.setCampusid(campusMap.get(cbxCampus.getSelectedItem().toString()));
            
            framePrincipal.add(telaCadastrarUsuario);
            telaCadastrarUsuario.setLocation(framePrincipal.getWidth()/2 - telaCadastrarUsuario.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCadastrarUsuario.getHeight()/2 - 20);
            telaCadastrarUsuario.setUsuarioEdicao(usuarioEdicao);
            telaCadastrarUsuario.setVisible(true);
            
        }
        else
        {
            telaCadastrarUsuario.setLocation(framePrincipal.getWidth()/2 - telaCadastrarUsuario.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCadastrarUsuario.getHeight()/2 - 20);
            telaCadastrarUsuario.setUsuarioEdicao(usuarioEdicao);
            telaCadastrarUsuario.setVisible(true);
        }
            
            telaCadastrarUsuario.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameClosing(InternalFrameEvent e) {
                }
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {}
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    telaCadastrarUsuario = null;
                    pesquisarTabelas(campusMap.get(cbxCampus.getSelectedItem().toString()));
                }
                @Override
                public void internalFrameIconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameActivated(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {}
        });
        
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed
    
    
    public void excluirEleicao(){
        if (tblEleicoes.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(rootPane, "É necessário escolher uma eleição para excluir !!", "Atenção !!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Conexao con = new Conexao();
        
        con.excluirEleicao(new Integer(tblEleicoes.getModel().getValueAt(tblEleicoes.getSelectedRow(), 0).toString()));
        
        pesquisarTabelas(campusMap.get(cbxCampus.getSelectedItem().toString()));
    
    
    }
    
    
    public void inicializarCriarCandidatura(){
        JDesktopPane framePrincipal = this.getDesktopPane();
  
    if(telaCriarCandidatura == null || telaCriarCandidatura.isClosed())        
    {
        telaCriarCandidatura = new CriarCandidatura();
        telaCriarCandidatura.setUsuarioCandidatura(this.adminLogado);
        telaCriarCandidatura.setCampusid(campusMap.get(cbxCampus.getSelectedItem().toString()));
        framePrincipal.add(telaCriarCandidatura);
        telaCriarCandidatura.setLocation(framePrincipal.getWidth()/2 - telaCriarCandidatura.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCriarCandidatura.getHeight()/2 - 20);
        telaCriarCandidatura.setVisible(true);
    }
    else
    {
        telaCriarCandidatura.setLocation(framePrincipal.getWidth()/2 - telaCriarCandidatura.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCriarCandidatura.getHeight()/2 - 20);
        telaCriarCandidatura.setVisible(true);
    }
    
    telaCriarCandidatura.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameClosing(InternalFrameEvent e) {}
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {}
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    telaCriarCandidatura = null;
                    pesquisarTabelas(campusMap.get(cbxCampus.getSelectedItem().toString()));
                
                }
                @Override
                public void internalFrameIconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameActivated(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {}
        });

    }
    
    public void excluirUsuario(Integer usuarioid){
        Conexao con = new Conexao();

        con.excluirUsuario(usuarioid);
        pesquisarTabelas(campusMap.get(cbxCampus.getSelectedItem().toString()));     
    
    }
    public void inicializarCadastrarUsuario(){
            JDesktopPane framePrincipal = this.getDesktopPane();
            
            if(telaCadastrarUsuario == null )        
        {
            telaCadastrarUsuario = new CadastrarUsuario();
            
            telaCadastrarUsuario.setCampusid(campusMap.get(cbxCampus.getSelectedItem().toString()));
            
            framePrincipal.add(telaCadastrarUsuario);
            telaCadastrarUsuario.setLocation(framePrincipal.getWidth()/2 - telaCadastrarUsuario.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCadastrarUsuario.getHeight()/2 - 20);
            telaCadastrarUsuario.setVisible(true);
        }
        else
        {
            telaCadastrarUsuario.setLocation(framePrincipal.getWidth()/2 - telaCadastrarUsuario.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCadastrarUsuario.getHeight()/2 - 20);
            telaCadastrarUsuario.setVisible(true);
        }
            
            telaCadastrarUsuario.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameClosing(InternalFrameEvent e) {
                }
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {}
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    telaCadastrarUsuario = null;
                    pesquisarTabelas(campusMap.get(cbxCampus.getSelectedItem().toString()));
                }
                @Override
                public void internalFrameIconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameActivated(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {}
        });
    
    }
    
    
    public void inicializarCriarEleicao(){
        JDesktopPane framePrincipal = this.getDesktopPane();
  
    if(telaCriarEleicao == null || telaCriarEleicao.isClosed())        
    {
        telaCriarEleicao = new CriarEleicao();
        telaCriarEleicao.setCampusid(campusMap.get(cbxCampus.getSelectedItem().toString()));
        framePrincipal.add(telaCriarEleicao);
        telaCriarEleicao.setLocation(framePrincipal.getWidth()/2 - telaCriarEleicao.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCriarEleicao.getHeight()/2 - 20);
        telaCriarEleicao.setVisible(true);
    }
    else
    {
        telaCriarEleicao.setLocation(framePrincipal.getWidth()/2 - telaCriarEleicao.getWidth()/2,(framePrincipal.getHeight()-20)/2 - telaCriarEleicao.getHeight()/2 - 20);
        telaCriarEleicao.setVisible(true);
    }
    
    telaCriarEleicao.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameClosing(InternalFrameEvent e) {}
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {}
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    telaCriarEleicao = null;
                    pesquisarTabelas(campusMap.get(cbxCampus.getSelectedItem().toString()));
                }
                @Override
                public void internalFrameIconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {}
                @Override
                public void internalFrameActivated(InternalFrameEvent e) {}
                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {}
        });

    
    }
    
    
    public void preencherCombBoxDescricao () {
        
        Conexao con = new Conexao();

        campusMap = con.getComboBoxCampus();

        Set<String> setmap = campusMap.keySet();
        
        
        setmap.forEach((key) -> {
            cbxCampus.addItem(key);
            
        });
        
        
         
    }
    
    
    public void pesquisarTabelas(Integer campusid){

        Conexao con = new Conexao();

        tblEleicoes.setModel(con.getTableEleicaoComCampus(campusid));
        tblEleicoes.removeColumn(tblEleicoes.getColumnModel().getColumn(0));

        tblUsuarios.setModel(con.getTableUsuariosExcetoUsuarioid(campusid,getAdminLogado().getId()) );
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(0));

        tblCandidatos.setModel(con.getTableUsuariosCandidatos(campusid));
        tblCandidatos.removeColumn(tblCandidatos.getColumnModel().getColumn(0));   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnCandidatarNovoUsuario;
    private javax.swing.JButton btnCriarEleicao;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JComboBox<String> cbxCampus;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCandidatos;
    private javax.swing.JTable tblEleicoes;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the adminLogado
     */
    public Usuario getAdminLogado() {
        return adminLogado;
    }

    /**
     * @param adminLogado the adminLogado to set
     */
    public void setAdminLogado(Usuario adminLogado) {
        this.adminLogado = adminLogado;
    }
}
