/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Candidatura;
import Models.Eleicao;
import Models.Usuario;
import Services.Conexao;
import java.util.ArrayList;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JOptionPane;

    
public class CriarCandidatura extends javax.swing.JInternalFrame {

    private Usuario usuarioLogado;
    private Integer campusid;
    public TreeMap<String, Integer> candidatosMap = new TreeMap<>();
    public TreeMap<String, Integer> eleicoesMap = new TreeMap<>();
    Conexao con;
    public CriarCandidatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtSlogan = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnVerificarCodigo = new javax.swing.JButton();
        cbxEleicao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnCriarCandidatura = new javax.swing.JButton();
        cbxCandidato = new javax.swing.JComboBox<>();
        lblInformeOEleitor = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.highlight")));
        setClosable(true);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(564, 567));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        pnFundo.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel1.setText("Dados para candidatura");

        edtSlogan.setColumns(20);
        edtSlogan.setRows(5);
        jScrollPane1.setViewportView(edtSlogan);

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel2.setText("Informe o SLOGAN");

        edtCodigo.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        edtCodigo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                edtCodigoInputMethodTextChanged(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel3.setText("Informe o número da candidatura");

        btnVerificarCodigo.setBackground(new java.awt.Color(0, 102, 255));
        btnVerificarCodigo.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnVerificarCodigo.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnVerificarCodigo.setText("Verificar disponibilidade");
        btnVerificarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarCodigoActionPerformed(evt);
            }
        });

        cbxEleicao.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        cbxEleicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- SELECIONE UMA ELEIÇÃO -" }));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel5.setText("Informe a eleição para cadastro");

        btnCriarCandidatura.setBackground(new java.awt.Color(0, 102, 255));
        btnCriarCandidatura.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnCriarCandidatura.setText("Confirmar Candidatura");
        btnCriarCandidatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarCandidaturaActionPerformed(evt);
            }
        });

        cbxCandidato.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        cbxCandidato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- SELECIONE UM CANDIDATO -" }));

        lblInformeOEleitor.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        lblInformeOEleitor.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        lblInformeOEleitor.setText("Informe o Candidato");

        javax.swing.GroupLayout pnFundoLayout = new javax.swing.GroupLayout(pnFundo);
        pnFundo.setLayout(pnFundoLayout);
        pnFundoLayout.setHorizontalGroup(
            pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFundoLayout.createSequentialGroup()
                        .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCriarCandidatura))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLayout.createSequentialGroup()
                                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(145, 145, 145)))
                                .addGroup(pnFundoLayout.createSequentialGroup()
                                    .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbxCandidato, 0, 240, Short.MAX_VALUE)
                                            .addComponent(cbxEleicao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pnFundoLayout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblInformeOEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)))
                                    .addGap(18, 18, 18)))))))
        );
        pnFundoLayout.setVerticalGroup(
            pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificarCodigo)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(lblInformeOEleitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnCriarCandidatura)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       preencherCombBoxEleicao();
       preencherCombBoxCandidato();   
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnVerificarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarCodigoActionPerformed
 
        con = new Conexao();
        
        if (!edtCodigo.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(rootPane, "Somente números são permitidos no código do candidato", "Aviso", JOptionPane.WARNING_MESSAGE);
          return;
            
        }

        if (con.existeCodigoCandidato(new Integer(edtCodigo.getText()))){
             btnVerificarCodigo.setText("Código já existe");
            edtCodigo.setText("");
        }else{
           btnVerificarCodigo.setText("Código disponível");
           btnVerificarCodigo.repaint();

        }
    
    }//GEN-LAST:event_btnVerificarCodigoActionPerformed

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed
        btnVerificarCodigo.setText("Verificar disponibilidade");
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void btnCriarCandidaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarCandidaturaActionPerformed
        
        if (!btnVerificarCodigo.getText().equals("Código disponível")){
        
          JOptionPane.showMessageDialog(rootPane, "É necessário escolher um código e validar", "Aviso", JOptionPane.WARNING_MESSAGE);
          return;
        }
        
        if (cbxCandidato.getSelectedItem().toString().equals("- SELECIONE UM CANDIDATO -")){
            JOptionPane.showMessageDialog(rootPane, "É necessário escolher um candidato válido para cadastrar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         if (cbxEleicao.getSelectedItem().toString().equals("- SELECIONE UMA ELEIÇÃO -")){
            JOptionPane.showMessageDialog(rootPane, "É necessário escolher uma eleição válida para cadastrar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        con = new Conexao();

        Eleicao eleicaoCandidato = new Eleicao(null, "", null, null);
        
        Integer eleicaoid = eleicoesMap.get(cbxEleicao.getSelectedItem().toString());
        Integer candidatoid =  candidatosMap.get(cbxCandidato.getSelectedItem().toString());
        eleicaoCandidato.setId(eleicaoid);

        Candidatura candidaturaUsuario = new Candidatura(edtSlogan.getText(), new Integer(edtCodigo.getText()), eleicaoCandidato);  
        
        con.criarCandidatura(candidaturaUsuario, candidatoid);
        this.dispose();
             

    }//GEN-LAST:event_btnCriarCandidaturaActionPerformed

    private void edtCodigoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_edtCodigoInputMethodTextChanged
        
    }//GEN-LAST:event_edtCodigoInputMethodTextChanged

    public void preencherCombBoxEleicao() {
        
        con = new Conexao();

        eleicoesMap = con.getComboBoxEleicao(this.usuarioLogado.getCampusId());
        cbxEleicao.removeAllItems();
        cbxEleicao.addItem("- SELECIONE UMA ELEIÇÃO -");
        
         Set<String> setmap = eleicoesMap.keySet();

        setmap.forEach((key) -> {
            cbxEleicao.addItem(key);
        });  

    }
    
    public void preencherCombBoxCandidato () {
        
        con = new Conexao();
        candidatosMap =con.getComboBoxUsuariosCandidatos(getCampusid());

        cbxCandidato.removeAllItems();
        cbxCandidato.addItem("- SELECIONE UM CANDIDATO -");
        
        Set<String> setmap = candidatosMap.keySet();
        
        
        setmap.forEach((key) -> {
            cbxCandidato.addItem(key);
            
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarCandidatura;
    private javax.swing.JButton btnVerificarCodigo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCandidato;
    private javax.swing.JComboBox<String> cbxEleicao;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextArea edtSlogan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInformeOEleitor;
    private javax.swing.JPanel pnFundo;
    // End of variables declaration//GEN-END:variables


    public void setUsuarioCandidatura(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }

  
    public Integer getCampusid() {
        return campusid;
    }

    
    public void setCampusid(Integer campusid) {
        this.campusid = campusid;
    }
}
