/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Candidatura;
import Models.Eleicao;
import Models.Eleitor;
import Models.Usuario;
import Models.Voto;
import Services.Conexao;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Altimar
 */
public class Votacao extends javax.swing.JInternalFrame {
    
    private Eleitor eleitor = null;
    public Votacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnVotacao = new javax.swing.JTabbedPane();
        pnEleicoes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEleicoes = new javax.swing.JTable();
        btnProximo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnCandidatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCandidatosElegiveis = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnVotar = new javax.swing.JButton();
        edtCodigoCandidato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnProximo1 = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnEleicoes.setBackground(new java.awt.Color(0, 51, 204));

        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel4.setText("Bem vindo ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel2.setText("Eleições disponiveis ");

        tblEleicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEleicoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEleicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEleicoesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEleicoes);

        btnProximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel6.setText("SELECIONE A OPÇÃO DESEJADA*");

        javax.swing.GroupLayout pnEleicoesLayout = new javax.swing.GroupLayout(pnEleicoes);
        pnEleicoes.setLayout(pnEleicoesLayout);
        pnEleicoesLayout.setHorizontalGroup(
            pnEleicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEleicoesLayout.createSequentialGroup()
                .addGroup(pnEleicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEleicoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEleicoesLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6))
                    .addGroup(pnEleicoesLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEleicoesLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEleicoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        pnEleicoesLayout.setVerticalGroup(
            pnEleicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEleicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tpnVotacao.addTab("tab1", pnEleicoes);

        pnCandidatos.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel1.setText("Bem vindo ");

        tblCandidatosElegiveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCandidatosElegiveis);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel5.setText("Candidatos elegiveis para votar");

        btnVotar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVotar.setText("CONFIRMAR VOTO");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });

        edtCodigoCandidato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel3.setText("DIGITE O CODIGO DO SEU CANDIDATO");

        btnProximo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProximo1.setText("Voltar");
        btnProximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCandidatosLayout = new javax.swing.GroupLayout(pnCandidatos);
        pnCandidatos.setLayout(pnCandidatosLayout);
        pnCandidatosLayout.setHorizontalGroup(
            pnCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCandidatosLayout.createSequentialGroup()
                .addGroup(pnCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCandidatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCandidatosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCandidatosLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel3))
                    .addGroup(pnCandidatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnProximo1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addGroup(pnCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtCodigoCandidato)
                            .addComponent(btnVotar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(pnCandidatosLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnCandidatosLayout.setVerticalGroup(
            pnCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCandidatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edtCodigoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pnCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximo1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tpnVotacao.addTab("tab1", pnCandidatos);

        getContentPane().add(tpnVotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -24, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        pesquisarEleicoes(); 
    }//GEN-LAST:event_formInternalFrameOpened
    
    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if (tblEleicoes.getSelectionModel().isSelectionEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Selecione uma eleição para continuar", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
    }
        pesquisarCandidatos();
        
        
        
        tpnVotacao.setSelectedIndex(1);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnProximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo1ActionPerformed
      tpnVotacao.setSelectedIndex(0);
    }//GEN-LAST:event_btnProximo1ActionPerformed

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        inserirVoto();
    }//GEN-LAST:event_btnVotarActionPerformed

    private void tblEleicoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEleicoesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEleicoesMouseClicked
    
    
    public Boolean candidatoValido(){
          
    for (int i = 0; i < tblCandidatosElegiveis.getRowCount(); i++) { 
    // Pega 5 coluna do model (index 4)
     if (tblCandidatosElegiveis.getValueAt(i, 3).toString().equals(edtCodigoCandidato.getText()))
        return true; 
    }  

    return false;
    }
    
    public void inserirVoto(){
        Conexao con = new Conexao();
        
        if (con.usuarioVotou(getEleitor().getId(), new Integer(tblEleicoes.getModel().getValueAt(tblEleicoes.getSelectedRow(), 0).toString()))){
            JOptionPane.showMessageDialog(rootPane, "Você já votou nesta eleição, não é possivel votar novamente", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            return;
        }
       
        if (!candidatoValido()){
            JOptionPane.showMessageDialog(rootPane, "Candidato não identificado, tente novamente", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Integer campusid = getEleitor().getCampusId();
        Date date = new Date();
        Eleicao eleicaoCandidato = new Eleicao( date.toString(),"", date.toString(), campusid);
         
        Candidatura candidaturaEscolhida = new Candidatura(title,
                new Integer(edtCodigoCandidato.getText()), eleicaoCandidato);
        
        candidaturaEscolhida.setId(con.getCandidaturaid(new Integer(edtCodigoCandidato.getText())));
         
        Voto votousuario = new Voto(this.eleitor, candidaturaEscolhida);
        con.criarVoto(votousuario);
        
        JOptionPane.showMessageDialog(rootPane, "Seu voto foi computado com sucesso!", "Voto computado",  JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }
    
    public void pesquisarEleicoes(){
        Conexao con = new Conexao();
   
    tblEleicoes.setModel(con.getTableEleicaoComCampus(eleitor.getCampusId()));
    tblEleicoes.removeColumn(tblEleicoes.getColumnModel().getColumn(0));
    tblEleicoes.removeColumn(tblEleicoes.getColumnModel().getColumn(0));
    }
    
    
    public void pesquisarCandidatos(){
        Conexao con = new Conexao();
        
    tblCandidatosElegiveis.setModel(con.getTableUsuariosCandidatos(Integer.valueOf(tblEleicoes.getModel().getValueAt(tblEleicoes.getSelectedRow(), 1).toString())));
    tblCandidatosElegiveis.removeColumn(tblCandidatosElegiveis.getColumnModel().getColumn(0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnProximo1;
    private javax.swing.JButton btnVotar;
    private javax.swing.JTextField edtCodigoCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnCandidatos;
    private javax.swing.JPanel pnEleicoes;
    private javax.swing.JTable tblCandidatosElegiveis;
    private javax.swing.JTable tblEleicoes;
    private javax.swing.JTabbedPane tpnVotacao;
    // End of variables declaration//GEN-END:variables

   
    public Eleitor getEleitor() {
        return eleitor;
    }

    public void setEleitor(Eleitor eleitor) {
        this.eleitor = eleitor;
    }
}
